# Generated by Django 3.2.5 on 2021-11-09 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='作业名称')),
                ('content', models.TextField(verbose_name='作业内容')),
                ('typ', models.CharField(choices=[('scrpit', '脚本'), ('playbook', 'ansible playbook')], max_length=30, verbose_name='脚本类型')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('status', models.CharField(choices=[('online', '上线'), ('offline', '下线')], max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'Job',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('hosts', models.JSONField(verbose_name='目标主机列表')),
                ('output', models.JSONField(verbose_name='任务输出')),
                ('jobs', models.JSONField(verbose_name='任务执行的作业列表')),
                ('exec_mode', models.CharField(choices=[('serial', '串行'), ('parallel', '并行')], max_length=30, verbose_name='作业执行方式')),
            ],
            options={
                'verbose_name': 'Task',
            },
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_time', models.DateTimeField(verbose_name='修改时间')),
                ('content', models.TextField(verbose_name='作业内容')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.job')),
            ],
            options={
                'verbose_name': 'Job_History',
            },
        ),
    ]
